apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-api-rest.fullname" . }}-cm
data:
  AZURE_STORAGE_ACCOUNT: {{ quote .Values.data.AZURE_STORAGE_ACCOUNT }}
  CONTAINER: {{ quote .Values.data.CONTAINER }}
  FILENAME: {{ quote .Values.data.FILENAME }}
  PAGINATION: {{ quote .Values.data.PAGINATION }}